apiVersion: v1
kind: Secret
metadata:
  name: knoxchat-secrets
  namespace: knoxchat
type: Opaque
data:
  SECRET_KEY: NTY0NjIxNzEwYjc0NjJmOGRlMDgyM2E4ZGUwMzA3OTA5YjJhZTRmOGE2NjdhMGU3ODY3NmFhNjZiYzdkYjdiNw0K